04.09.2019 09:55:28 Checking for system tray...
04.09.2019 09:55:28 Starting pgAdmin4 server...
04.09.2019 09:55:28 Creating server object, port:50291, key:43339fb4-e749-440d-a83f-68bbd0a3cca1, logfile:C:/Users/sv/.pgAdmin4.2123502176.log
04.09.2019 09:55:28 Python Path: C:/Program Files/PostgreSQL/10/pgAdmin 4/venv/Lib/site-packages;C:/Program Files/PostgreSQL/10/pgAdmin 4/venv/DLLs;C:/Program Files/PostgreSQL/10/pgAdmin 4/venv/Lib
04.09.2019 09:55:28 Python Home: C:/Program Files/PostgreSQL/10/pgAdmin 4/venv
04.09.2019 09:55:28 Initializing Python...
04.09.2019 09:55:28 Python initialized.
04.09.2019 09:55:28 Adding new additional path elements
04.09.2019 09:55:28 Redirecting stderr...
04.09.2019 09:55:28 stderr redirected successfully.
04.09.2019 09:55:28 Initializing server...
04.09.2019 09:55:28 Webapp Path: C:/Program Files/PostgreSQL/10/pgAdmin 4/web/pgAdmin4.py
04.09.2019 09:55:28 Server initialized.
04.09.2019 09:55:28 Starting Server Thread...
04.09.2019 09:55:28 Open the application code and run it.
04.09.2019 09:55:28 Set the port number, key and force SERVER_MODE off
04.09.2019 09:55:28 PyRun_SimpleFile launching application server...
04.09.2019 09:55:29 Application Server URL: http://127.0.0.1:50291/?key=43339fb4-e749-440d-a83f-68bbd0a3cca1
04.09.2019 09:55:29 The server should be up, we'll attempt to connect and get a response. Ping the server
04.09.2019 09:56:28 Attempt to connect one more time in case of a long network timeout while looping
04.09.2019 09:56:28 Everything works fine, successfully started pgAdmin4.
